version: '2'

volumes:
    # database data volume
    database-data:
      driver: local

services:
  # jail container used to detonate terminal commands on telnet and ssh
  jail:
    image: busybox
    command: ["tail", "-f", "/dev/null"]
    container_name: jail

  # the sexiest honeypot in the multiverse
  medusa:
    build: .
    network_mode: host
    volumes:
      # this is where medusa generates SSH keys, persist it to avoid known-hosts fingerprint collissions
      - /tmp:/tmp
      - ./compose/medusa/records:/var/lib/medusa/records
      - ./compose/medusa/services.d:/etc/medusa/services.d
      - ./compose/medusa/medusa-https.crt:/etc/medusa/https.crt
      - ./compose/medusa/medusa-https.key:/etc/medusa/https.key
      # medusa needs access to the docker socket in order to use the jail mechanism
      - /var/run/docker.sock:/var/run/docker.sock

  # the sexiest all-in-one tool in the multiverse
  driplane:
    build: https://github.com/Matrix86/driplane.git
    command: -config /etc/driplane/config.yml
    volumes:
      - ./compose/driplane:/etc/driplane
      - ./compose/medusa/records:/var/lib/medusa/records
    network_mode: host

  # elasticsearch database
  database:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    hostname: localhost
    container_name: db
    command: ["elasticsearch", "-Elogger.level=WARN"]
    environment:
      - cluster.name=docker-cluster
      - node.name=es01
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - database-data:/usr/share/elasticsearch/data
    network_mode: host
    
  # dashboard
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: webui
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://localhost:9200/
      ELASTICSEARCH_HOSTS: '["http://localhost:9200"]'
    ports:
      - 5601:5601
    network_mode: host
    depends_on:
      - database      
    logging:
      driver: none